name: Terraform CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read
  pull-requests: write

env:
  AWS_REGION: us-east-1
  TF_VERSION: 1.13.3

jobs:
  lint:
    name: Terraform Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - run: echo "checking out the code"
  
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ vars.TF_VERSION }}
      - run: echo "setting up Terraform"
      
      - name: Check Terraform formatting
        run: terraform fmt -check -recursive
      - run: echo "checking that formatting"
  
      - name: Install TFLint
        uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: latest
      - run: echo "installing TFLint"
  
      - name: Run TFLint
        run: |
          tflint --init
          tflint
      - run: echo "running TFLint"
      
  plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    needs: lint
    environment: staging
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - run: echo "checking out the code"
  
      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ vars.AWS_REGION }}
      - run: echo "configuring the aws credentials"
  
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ vars.TF_VERSION }}
      - run: echo "setting up Terraform"
  
      - name: Terraform Init
        run: terraform init
      - run: echo "initializing Terraform"
  
      - name: Terraform Plan
        run: terraform plan -out=tfplan.binary
      - run: echo "running that Terraform Plan"
  
      - name: Upload Plan Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: tfplan.binary
      - run: echo "uploading the Plan Artifact"


  apply:
    name: Terraform Apply (Manual Approval)
    runs-on: ubuntu-latest
    needs: plan
    environment:
      name: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - run: echo "checking out the code"

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}
      - run: echo "configuring the aws credentials"

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}
      - run: echo "setting up Terraform"

      - name: Terraform Init
        run: terraform init
      - run: echo "initializing Terraform"

      - name: Download Plan Artifact
        uses: actions/download-artifact@v4
        with:
          name: tfplan
      - run: echo "downloading the Plan Artifact"

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan.binary
      - run: echo "running that Terraform Apply"
